### ISSUE TITLE
Models properties does not contain all items specified in API documentation

### ISSUE THREAD

**Issue by Th3An1m4l** [moxiworks-platform/moxiworks-php#4]
Please review Models and update with ALL specified in API properties.

For example: Status  in Listing, UUID on Agent, and etc. Since we use moxiworks-php trhought composer and it not suitable to make changes manually. Everything should be from the box.

**Comment by tres** [comment]
Hi @Th3An1m4l 

Thanks for your report. 

I'll work to integrate the missing attributes you've pointed out. 

If you have any other attributes you notice missing, please let us know. 

Thanks,
Tres

**Comment by tres** [comment]
@Th3An1m4l It looks like Agent.php already has a $uuid attribute. 

I've updated Listing with $status, $listing_url and $company_listing_attributes & have pushed 0.13.2. 

https://packagist.org/packages/moxiworks/moxiworks_platform

Thanks again for your report!

Please let us know if there's anything else we can do. 

Regards,
Tres

**Comment by Th3An1m4l** [comment]
Hi @tres , could you please add **ALL properties**  specified in API (http://moxiworks-platform.github.io/?php#moxi-works-api-1-14-1) properties for next models

MoxiworksPlatform\Credentials
MoxiworksPlatform\Company
MoxiworksPlatform\SoldListing
MoxiworksPlatform\Listing (open_house, virtual_tour_url, title : missing)
MoxiworksPlatform\Agent
MoxiworksPlatform\Office

to avoid each time we need something from the list call you again.

**Comment by tres** [comment]
Hey @Th3An1m4l,

Thanks for getting back with us about the missing attributes. 

A general request to ensure parity will take some time as it needs to be routed through our QA department. 

Specific issues can be resolved quicker. 

I'll reopen this issue and add the noted missing attributes. 

Thanks again for your report!

**Comment by tres** [comment]
@Th3An1m4l  I've pushed version 0.13.3 of the PHP library. It should be available via packagist now:

https://packagist.org/packages/moxiworks/moxiworks_platform

This update incorporates the requested listing attributes. 

Additionally, I've created a request for our QA team to check parity of the available attributes in the listed entities. 

I'll leave this ticket open until they've had an opportunity to review the libraries.

Thanks,
Tres

**Comment by Th3An1m4l** [comment]
MoxiworksPlatform\Office - office_website | still missing
MoxiworksPlatform\Listing - status, listing_url, virtual_tour_url, title | still missing
MoxiworksPlatform\SoldListing - title,CompanyListingAttributes | still missing

not sure for another, but still. It need to be defined in models all that present in API definition.

**Comment by Th3An1m4l** [comment]
MoxiworksPlatform\Office | office_website missing|
MoxiworksPlatform\Listing | title, missing
MoxiworksPlatform\SoldListing | CompanyListingAttributes, lisintg_url and others, please follow API for the full list to avoid report each time when field is missing.

**Comment by tres** [comment]
@Th3An1m4l all Listing attributes except *title* should already have been in 0.13.3. 

https://github.com/moxiworks-platform/moxiworks-php/commit/a8cbc7202efabf37bde5764f74427f3707409bfd#diff-52a15d8effca257ffe726e8a79195a28R277

https://github.com/moxiworks-platform/moxiworks-php/commit/a8cbc7202efabf37bde5764f74427f3707409bfd#diff-52a15d8effca257ffe726e8a79195a28R332

It looks like *title* didn't make it into the heads-up list of attributes & example (which is why *title* didn't make it into 0.13.3). I've also corrected that & published 1.15.1 of the platform docs. 

Thanks! Let us know if there's anything else we can do.

Keeping this open until our QA team has looked at the requested entities to ensure parity between libraries and documentation.

0.13.4 should be available at packagist

https://packagist.org/packages/moxiworks/moxiworks_platform

**Comment by Th3An1m4l** [comment]
status and lisiting_url missed in SoldListing Model

**Comment by Th3An1m4l** [comment]
/**
     * @string Details URL for this listing.
     */
    public $listing_url;


    /**
     * @var string Detailed status of the listing; whether it’s active pending
     */
    public $status;

**Comment by tres** [comment]
Hey @Th3An1m4l ,

I've updated with your code and pushed 0.13.10 which should be available via packagist. 

https://packagist.org/packages/moxiworks/moxiworks_platform

Thanks!

Tres

**Comment by tres** [comment]
@Th3An1m4l 

I've pushed updates in 0.13.11 that should include any missing attributes.

props to @tayleighr for going over everything.
